import type {
	StickyColumnConfig,
	TableConfig,
} from "@/components/tables-2/core";
import { sizes } from "@/components/tables-2/core/table-sizes";
import type { TableId } from "@/utils/table-settings";

export const TABLE_CONFIGS: Record<TableId, TableConfig> = {
	"sales-orders": {
		tableId: "sales-orders",
		stickyColumns: [
			{ id: "select", width: sizes.custom(50, 50).size },
			{ id: "orderId", width: sizes.custom(150, 280, 180).size },
		],
		sortFieldMap: {
			orderId: "orderId",
			status: "status",
			salesDate: "createdAt",
			customerName: "customerName",
			invoiceTotal: "grandTotal",
			amountDue: "amountDue",
			productionLabel: "prodStatus",
			fulfillmentLabel: "deliveredAt",
			salesRepName: "salesRepName",
		},
		nonReorderableColumns: new Set(["select", "orderId", "actions"]),
		rowHeight: 40,
		headerHeight: 45,
		style: "compact",
		summaryGridHeight: 180,
	},
	"sales-quotes": {
		tableId: "sales-quotes",
		stickyColumns: [
			{ id: "select", width: sizes.custom(50, 50).size },
			{ id: "orderId", width: sizes.custom(150, 280, 180).size },
		],
		sortFieldMap: {
			orderId: "orderId",
			salesDate: "createdAt",
			invoiceTotal: "grandTotal",
		},
		nonReorderableColumns: new Set(["select", "orderId", "actions"]),
		rowHeight: 40,
		headerHeight: 45,
		style: "compact",
	},
	customers: {
		tableId: "customers",
		stickyColumns: [
			{ id: "customer", width: sizes.custom(180, 320, 220).size },
		],
		sortFieldMap: {
			customer: "name",
			phoneNo: "phoneNo",
			email: "email",
			address: "address",
		},
		nonReorderableColumns: new Set(["customer", "actions"]),
		rowHeight: 48,
		headerHeight: 45,
		style: "compact",
	},
	"customer-transactions": {
		tableId: "customer-transactions",
		stickyColumns: [{ id: "date", width: sizes.custom(150, 230, 170).size }],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["date", "actions"]),
		rowHeight: 64,
		headerHeight: 45,
		style: "compact",
	},
	"customer-pay-portal": {
		tableId: "customer-pay-portal",
		stickyColumns: [
			{ id: "selected", width: sizes.custom(50, 50, 50).size },
			{ id: "order", width: sizes.custom(132, 220, 154).size },
		],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["selected", "order", "actions"]),
		rowHeight: 48,
		headerHeight: 45,
		style: "compact",
	},
	"customer-sales-list": {
		tableId: "customer-sales-list",
		stickyColumns: [{ id: "date", width: sizes.custom(112, 170, 128).size }],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["date", "actions"]),
		rowHeight: 48,
		headerHeight: 45,
		style: "compact",
	},
	"customer-sales-workspace": {
		tableId: "customer-sales-workspace",
		stickyColumns: [
			{ id: "select", width: sizes.custom(50, 50, 50).size },
			{ id: "order", width: sizes.custom(132, 220, 154).size },
		],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["select", "order", "actions"]),
		rowHeight: 40,
		headerHeight: 45,
		style: "compact",
	},
	"customer-overview-sales-preview": {
		tableId: "customer-overview-sales-preview",
		stickyColumns: [
			{ id: "reference", width: sizes.custom(150, 260, 180).size },
		],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["reference", "actions"]),
		rowHeight: 56,
		headerHeight: 45,
		style: "compact",
	},
	"customer-statement-report": {
		tableId: "customer-statement-report",
		stickyColumns: [
			{ id: "customer", width: sizes.custom(220, 420, 280).size },
		],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["customer", "actions"]),
		rowHeight: 56,
		headerHeight: 45,
		style: "compact",
	},
	"customer-statement-lines": {
		tableId: "customer-statement-lines",
		stickyColumns: [
			{ id: "select", width: sizes.custom(50, 50, 50).size },
			{ id: "order", width: sizes.custom(112, 170, 132).size },
		],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["select", "order", "actions"]),
		rowHeight: 48,
		headerHeight: 45,
		style: "compact",
	},
	"door-suppliers": {
		tableId: "door-suppliers",
		stickyColumns: [
			{ id: "selected", width: sizes.custom(50, 50, 50).size },
			{ id: "supplier", width: sizes.custom(180, 320, 220).size },
		],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["selected", "supplier", "actions"]),
		rowHeight: 48,
		headerHeight: 45,
		style: "compact",
	},
	"clean-code-door-size-select-lines": {
		tableId: "clean-code-door-size-select-lines",
		stickyColumns: [{ id: "size", width: sizes.custom(116, 190, 136).size }],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["size", "qty", "rh"]),
		rowHeight: 52,
		headerHeight: 45,
		style: "compact",
	},
	"sales-form-takeoff-hpt-lines": {
		tableId: "sales-form-takeoff-hpt-lines",
		stickyColumns: [{ id: "size", width: sizes.custom(128, 220, 150).size }],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["size", "total"]),
		rowHeight: 52,
		headerHeight: 45,
		style: "compact",
	},
	"sales-form-hpt-lines": {
		tableId: "sales-form-hpt-lines",
		stickyColumns: [{ id: "size", width: sizes.custom(112, 190, 132).size }],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["sn", "size", "actions"]),
		rowHeight: 48,
		headerHeight: 45,
		style: "compact",
	},
	"sales-form-moulding-lines": {
		tableId: "sales-form-moulding-lines",
		stickyColumns: [
			{ id: "moulding", width: sizes.custom(200, 380, 260).size },
		],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["sn", "moulding", "actions"]),
		rowHeight: 48,
		headerHeight: 45,
		style: "compact",
	},
	"clean-code-sales-form-moulding-lines": {
		tableId: "clean-code-sales-form-moulding-lines",
		stickyColumns: [
			{ id: "moulding", width: sizes.custom(200, 380, 260).size },
		],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["sn", "moulding", "actions"]),
		rowHeight: 48,
		headerHeight: 45,
		style: "compact",
	},
	"sales-form-service-lines": {
		tableId: "sales-form-service-lines",
		stickyColumns: [{ id: "service", width: sizes.custom(220, 420, 280).size }],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["sn", "service", "actions"]),
		rowHeight: 48,
		headerHeight: 45,
		style: "compact",
	},
	"clean-code-sales-form-service-lines": {
		tableId: "clean-code-sales-form-service-lines",
		stickyColumns: [
			{ id: "description", width: sizes.custom(220, 420, 280).size },
		],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["sn", "description", "actions"]),
		rowHeight: 48,
		headerHeight: 45,
		style: "compact",
	},
	"sales-form-shelf-items": {
		tableId: "sales-form-shelf-items",
		stickyColumns: [
			{ id: "category", width: sizes.custom(210, 360, 260).size },
		],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["sn", "category", "actions"]),
		rowHeight: 56,
		headerHeight: 45,
		style: "compact",
	},
	"builder-form-tasks": {
		tableId: "builder-form-tasks",
		stickyColumns: [{ id: "task", width: sizes.custom(220, 420, 280).size }],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["task", "actions"]),
		rowHeight: 48,
		headerHeight: 45,
		style: "compact",
	},
	"role-form-permissions": {
		tableId: "role-form-permissions",
		stickyColumns: [
			{ id: "permission", width: sizes.custom(240, 420, 300).size },
		],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["permission"]),
		rowHeight: 48,
		headerHeight: 45,
		style: "compact",
	},
	"employee-form-permissions": {
		tableId: "employee-form-permissions",
		stickyColumns: [
			{ id: "permission", width: sizes.custom(240, 420, 300).size },
		],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["permission"]),
		rowHeight: 48,
		headerHeight: 45,
		style: "compact",
	},
	"job-scope": {
		tableId: "job-scope",
		stickyColumns: [{ id: "task", width: sizes.custom(220, 420, 280).size }],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["task"]),
		rowHeight: 48,
		headerHeight: 45,
		style: "compact",
	},
	"new-job-install-tasks": {
		tableId: "new-job-install-tasks",
		stickyColumns: [{ id: "task", width: sizes.custom(220, 420, 280).size }],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["task", "qty"]),
		rowHeight: 56,
		headerHeight: 45,
		style: "compact",
	},
	"inventory-product-form-variants": {
		tableId: "inventory-product-form-variants",
		stickyColumns: [{ id: "variant", width: sizes.custom(220, 420, 280).size }],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["variant", "actions"]),
		rowHeight: 52,
		headerHeight: 45,
		style: "compact",
	},
	"inventory-product-form-sub-components": {
		tableId: "inventory-product-form-sub-components",
		stickyColumns: [
			{ id: "handle", width: sizes.custom(48, 48, 48).size },
			{ id: "category", width: sizes.custom(220, 360, 260).size },
		],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["handle", "category", "actions"]),
		rowHeight: 52,
		headerHeight: 45,
		style: "compact",
	},
	"unit-invoice-form-tasks": {
		tableId: "unit-invoice-form-tasks",
		stickyColumns: [{ id: "task", width: sizes.custom(240, 420, 300).size }],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["task", "actions"]),
		rowHeight: 52,
		headerHeight: 45,
		style: "compact",
	},
	"community-model-cost-form-tasks": {
		tableId: "community-model-cost-form-tasks",
		stickyColumns: [{ id: "task", width: sizes.custom(240, 420, 300).size }],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["task"]),
		rowHeight: 48,
		headerHeight: 45,
		style: "compact",
	},
	"community-install-cost-form-tasks": {
		tableId: "community-install-cost-form-tasks",
		stickyColumns: [{ id: "task", width: sizes.custom(240, 420, 300).size }],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["task"]),
		rowHeight: 48,
		headerHeight: 45,
		style: "compact",
	},
	dealers: {
		tableId: "dealers",
		stickyColumns: [{ id: "dealer", width: sizes.custom(180, 320, 220).size }],
		sortFieldMap: {
			dealer: "name",
			email: "email",
			status: "status",
			createdAt: "createdAt",
		},
		nonReorderableColumns: new Set(["dealer", "actions"]),
		rowHeight: 48,
		headerHeight: 45,
		style: "compact",
	},
	employees: {
		tableId: "employees",
		stickyColumns: [
			{ id: "employee", width: sizes.custom(240, 460, 320).size },
		],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["employee", "actions"]),
		rowHeight: 64,
		headerHeight: 45,
		style: "compact",
	},
	roles: {
		tableId: "roles",
		stickyColumns: [{ id: "role", width: sizes.custom(180, 320, 220).size }],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["role", "actions"]),
		rowHeight: 56,
		headerHeight: 45,
		style: "compact",
	},
	"employee-profiles": {
		tableId: "employee-profiles",
		stickyColumns: [{ id: "profile", width: sizes.custom(190, 340, 230).size }],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["profile", "actions"]),
		rowHeight: 56,
		headerHeight: 45,
		style: "compact",
	},
	"contractor-jobs": {
		tableId: "contractor-jobs",
		stickyColumns: [
			{ id: "select", width: sizes.custom(50, 50).size },
			{ id: "job", width: sizes.custom(150, 260, 180).size },
		],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["select", "job", "actions"]),
		rowHeight: 64,
		headerHeight: 45,
		style: "compact",
	},
	"contractor-payouts": {
		tableId: "contractor-payouts",
		stickyColumns: [
			{ id: "select", width: sizes.custom(50, 50).size },
			{ id: "date", width: sizes.custom(150, 240, 170).size },
		],
		sortFieldMap: {
			date: "date",
			paidTo: "paidTo",
			authorizedBy: "authorizedBy",
			amount: "amount",
		},
		nonReorderableColumns: new Set(["select", "date", "actions"]),
		rowHeight: 64,
		headerHeight: 45,
		style: "compact",
	},
	"contractor-payout-overview-jobs": {
		tableId: "contractor-payout-overview-jobs",
		stickyColumns: [{ id: "job", width: sizes.custom(220, 420, 280).size }],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["job"]),
		rowHeight: 64,
		headerHeight: 45,
		style: "compact",
	},
	"payment-dashboard-contractors": {
		tableId: "payment-dashboard-contractors",
		stickyColumns: [
			{ id: "contractor", width: sizes.custom(200, 360, 250).size },
		],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["contractor", "actions"]),
		rowHeight: 56,
		headerHeight: 45,
		style: "compact",
	},
	"payment-dashboard-recent-payments": {
		tableId: "payment-dashboard-recent-payments",
		stickyColumns: [{ id: "payout", width: sizes.custom(136, 220, 156).size }],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["payout", "actions"]),
		rowHeight: 56,
		headerHeight: 45,
		style: "compact",
	},
	"payment-portal-jobs": {
		tableId: "payment-portal-jobs",
		stickyColumns: [
			{ id: "select", width: sizes.custom(50, 50, 50).size },
			{ id: "job", width: sizes.custom(132, 210, 154).size },
		],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["select", "job", "actions"]),
		rowHeight: 64,
		headerHeight: 45,
		style: "compact",
	},
	"site-actions": {
		tableId: "site-actions",
		stickyColumns: [
			{ id: "select", width: sizes.custom(50, 50).size },
			{ id: "createdAt", width: sizes.custom(150, 230, 170).size },
		],
		sortFieldMap: {
			createdAt: "createdAt",
			event: "event",
			activity: "description",
			reference: "id",
		},
		nonReorderableColumns: new Set(["select", "createdAt"]),
		rowHeight: 56,
		headerHeight: 45,
		style: "compact",
	},
	"short-links": {
		tableId: "short-links",
		stickyColumns: [
			{ id: "select", width: sizes.custom(50, 50).size },
			{ id: "shortLink", width: sizes.custom(220, 420, 280).size },
		],
		sortFieldMap: {
			shortLink: "slug",
			target: "targetUrl",
			status: "active",
			clicks: "clickCount",
			lastClick: "lastClickedAt",
			expiry: "expiresAt",
		},
		nonReorderableColumns: new Set(["select", "shortLink", "actions"]),
		rowHeight: 64,
		headerHeight: 45,
		style: "compact",
	},
	"packing-list": {
		tableId: "packing-list",
		stickyColumns: [{ id: "orderNo", width: sizes.custom(150, 220, 170).size }],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["orderNo", "actions"]),
		rowHeight: 64,
		headerHeight: 45,
		style: "compact",
	},
	"shelf-items": {
		tableId: "shelf-items",
		stickyColumns: [{ id: "product", width: sizes.custom(200, 360, 240).size }],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["product", "actions"]),
		rowHeight: 56,
		headerHeight: 45,
		style: "compact",
	},
	"sales-email-ledger": {
		tableId: "sales-email-ledger",
		stickyColumns: [{ id: "status", width: sizes.custom(142, 210, 160).size }],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["status", "actions"]),
		rowHeight: 56,
		headerHeight: 45,
		style: "compact",
	},
	"task-events": {
		tableId: "task-events",
		stickyColumns: [{ id: "event", width: sizes.custom(260, 520, 340).size }],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["event", "actions"]),
		rowHeight: 64,
		headerHeight: 45,
		style: "compact",
	},
	"task-run-diagnostics": {
		tableId: "task-run-diagnostics",
		stickyColumns: [{ id: "status", width: sizes.custom(128, 196, 148).size }],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["status", "actions"]),
		rowHeight: 56,
		headerHeight: 45,
		style: "compact",
	},
	"task-event-history": {
		tableId: "task-event-history",
		stickyColumns: [{ id: "time", width: sizes.custom(136, 210, 156).size }],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["time"]),
		rowHeight: 112,
		headerHeight: 45,
		style: "compact",
	},
	"document-approvals": {
		tableId: "document-approvals",
		stickyColumns: [
			{ id: "employee", width: sizes.custom(180, 320, 220).size },
		],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["employee", "actions"]),
		rowHeight: 56,
		headerHeight: 45,
		style: "compact",
	},
	"bug-reports": {
		tableId: "bug-reports",
		stickyColumns: [{ id: "report", width: sizes.custom(220, 420, 280).size }],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["report", "actions"]),
		rowHeight: 64,
		headerHeight: 45,
		style: "compact",
	},
	"bug-report-access-employees": {
		tableId: "bug-report-access-employees",
		stickyColumns: [
			{ id: "employee", width: sizes.custom(220, 420, 280).size },
		],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["employee", "access"]),
		rowHeight: 56,
		headerHeight: 45,
		style: "compact",
	},
	"notification-channels": {
		tableId: "notification-channels",
		stickyColumns: [{ id: "channel", width: sizes.custom(240, 420, 300).size }],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["channel", "actions"]),
		rowHeight: 56,
		headerHeight: 45,
		style: "compact",
	},
	"master-password-logins": {
		tableId: "master-password-logins",
		stickyColumns: [{ id: "user", width: sizes.custom(220, 420, 280).size }],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["user", "actions"]),
		rowHeight: 64,
		headerHeight: 45,
		style: "compact",
	},
	"user-logged-in-devices": {
		tableId: "user-logged-in-devices",
		stickyColumns: [{ id: "device", width: sizes.custom(180, 320, 220).size }],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["device", "actions"]),
		rowHeight: 40,
		headerHeight: 45,
		style: "compact",
	},
	"legacy-square-payment-orders": {
		tableId: "legacy-square-payment-orders",
		stickyColumns: [{ id: "invoice", width: sizes.custom(112, 160, 128).size }],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["invoice"]),
		rowHeight: 40,
		headerHeight: 45,
		style: "compact",
	},
	"sales-rep-design-activity": {
		tableId: "sales-rep-design-activity",
		stickyColumns: [{ id: "order", width: sizes.custom(112, 170, 132).size }],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["order"]),
		rowHeight: 48,
		headerHeight: 45,
		style: "compact",
	},
	"transaction-overview-applications": {
		tableId: "transaction-overview-applications",
		stickyColumns: [{ id: "invoice", width: sizes.custom(104, 150, 118).size }],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["invoice"]),
		rowHeight: 40,
		headerHeight: 45,
		style: "compact",
	},
	"transaction-overview-payments": {
		tableId: "transaction-overview-payments",
		stickyColumns: [{ id: "date", width: sizes.custom(108, 150, 124).size }],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["date", "actions"]),
		rowHeight: 48,
		headerHeight: 45,
		style: "compact",
	},
	"sales-rep-commission-payments": {
		tableId: "sales-rep-commission-payments",
		stickyColumns: [
			{ id: "paymentId", width: sizes.custom(150, 240, 170).size },
		],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["paymentId", "receipt"]),
		rowHeight: 56,
		headerHeight: 45,
		style: "compact",
	},
	"sales-rep-commissions": {
		tableId: "sales-rep-commissions",
		stickyColumns: [
			{ id: "paymentId", width: sizes.custom(150, 240, 170).size },
		],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["paymentId"]),
		rowHeight: 56,
		headerHeight: 45,
		style: "compact",
	},
	"community-projects": {
		tableId: "community-projects",
		stickyColumns: [
			{ id: "select", width: sizes.custom(50, 50).size },
			{ id: "project", width: sizes.custom(240, 460, 320).size },
		],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["select", "project", "actions"]),
		rowHeight: 64,
		headerHeight: 45,
		style: "compact",
	},
	"project-units": {
		tableId: "project-units",
		stickyColumns: [
			{ id: "select", width: sizes.custom(50, 50).size },
			{ id: "lotBlock", width: sizes.custom(220, 380, 280).size },
		],
		sortFieldMap: {
			date: "date",
			project: "project",
			lotBlock: "lotBlock",
		},
		nonReorderableColumns: new Set(["select", "lotBlock", "actions"]),
		rowHeight: 64,
		headerHeight: 45,
		style: "compact",
	},
	"sales-dispatch": {
		tableId: "sales-dispatch",
		stickyColumns: [
			{ id: "select", width: sizes.custom(50, 50).size },
			{ id: "orderId", width: sizes.custom(140, 230, 160).size },
		],
		sortFieldMap: {
			orderId: "orderId",
			dueDate: "dueDate",
			orderDate: "createdAt",
			status: "status",
			assignedTo: "driverId",
		},
		nonReorderableColumns: new Set(["select", "orderId", "actions"]),
		rowHeight: 56,
		headerHeight: 45,
		style: "compact",
	},
	"inbound-management": {
		tableId: "inbound-management",
		stickyColumns: [{ id: "orderId", width: sizes.custom(132, 220, 154).size }],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["orderId", "actions"]),
		rowHeight: 56,
		headerHeight: 45,
		style: "compact",
	},
	"sales-inbounds": {
		tableId: "sales-inbounds",
		stickyColumns: [{ id: "inbound", width: sizes.custom(190, 340, 240).size }],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["inbound", "actions"]),
		rowHeight: 64,
		headerHeight: 45,
		style: "compact",
	},
	"sales-accounting": {
		tableId: "sales-accounting",
		stickyColumns: [
			{ id: "select", width: sizes.custom(50, 50).size },
			{ id: "createdAt", width: sizes.custom(118, 180, 136).size },
		],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["select", "createdAt", "actions"]),
		rowHeight: 56,
		headerHeight: 45,
		style: "compact",
	},
	"sales-resolution": {
		tableId: "sales-resolution",
		stickyColumns: [
			{ id: "select", width: sizes.custom(50, 50).size },
			{ id: "orderId", width: sizes.custom(132, 220, 154).size },
		],
		sortFieldMap: {
			orderId: "orderId",
			amounts: "grandTotal",
			due: "amountDue",
		},
		nonReorderableColumns: new Set(["select", "orderId", "actions"]),
		rowHeight: 56,
		headerHeight: 45,
		style: "compact",
	},
	"sales-production": {
		tableId: "sales-production",
		stickyColumns: [{ id: "dueDate", width: sizes.custom(140, 200, 160).size }],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["dueDate", "actions"]),
		rowHeight: 64,
		headerHeight: 45,
		style: "compact",
	},
	"sales-statistics": {
		tableId: "sales-statistics",
		stickyColumns: [
			{ id: "productName", width: sizes.custom(200, 380, 240).size },
		],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["productName"]),
		rowHeight: 56,
		headerHeight: 45,
		style: "compact",
	},
	"inventory-products": {
		tableId: "inventory-products",
		stickyColumns: [
			{ id: "select", width: sizes.custom(50, 50).size },
			{ id: "product", width: sizes.custom(260, 520, 320).size },
		],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["select", "product", "actions"]),
		rowHeight: 72,
		headerHeight: 45,
		style: "compact",
	},
	"inventory-categories": {
		tableId: "inventory-categories",
		stickyColumns: [
			{ id: "select", width: sizes.custom(50, 50).size },
			{ id: "category", width: sizes.custom(260, 520, 320).size },
		],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["select", "category", "actions"]),
		rowHeight: 64,
		headerHeight: 45,
		style: "compact",
	},
	"inventory-suppliers": {
		tableId: "inventory-suppliers",
		stickyColumns: [
			{ id: "supplier", width: sizes.custom(220, 420, 280).size },
		],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["supplier", "actions"]),
		rowHeight: 56,
		headerHeight: 45,
		style: "compact",
	},
	"inventory-import": {
		tableId: "inventory-import",
		stickyColumns: [
			{ id: "category", width: sizes.custom(260, 540, 340).size },
		],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["category"]),
		rowHeight: 72,
		headerHeight: 45,
		style: "compact",
	},
	"inventory-allocations": {
		tableId: "inventory-allocations",
		stickyColumns: [
			{ id: "select", width: sizes.custom(50, 50).size },
			{ id: "inventory", width: sizes.custom(240, 480, 300).size },
		],
		sortFieldMap: {
			createdAt: "createdAt",
		},
		nonReorderableColumns: new Set(["select", "inventory", "actions"]),
		rowHeight: 64,
		headerHeight: 45,
		style: "compact",
	},
	"inventory-variants": {
		tableId: "inventory-variants",
		stickyColumns: [{ id: "variant", width: sizes.custom(260, 500, 320).size }],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["variant", "actions"]),
		rowHeight: 64,
		headerHeight: 45,
		style: "compact",
	},
	"inventory-backorders": {
		tableId: "inventory-backorders",
		stickyColumns: [{ id: "order", width: sizes.custom(160, 280, 190).size }],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["order", "actions"]),
		rowHeight: 56,
		headerHeight: 45,
		style: "compact",
	},
	"inventory-inbounds": {
		tableId: "inventory-inbounds",
		stickyColumns: [{ id: "inbound", width: sizes.custom(190, 340, 240).size }],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["inbound", "actions"]),
		rowHeight: 64,
		headerHeight: 45,
		style: "compact",
	},
	"inventory-partial-shipments": {
		tableId: "inventory-partial-shipments",
		stickyColumns: [{ id: "order", width: sizes.custom(160, 280, 190).size }],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["order", "hold", "actions"]),
		rowHeight: 56,
		headerHeight: 45,
		style: "compact",
	},
	"inventory-dispatch-mode": {
		tableId: "inventory-dispatch-mode",
		stickyColumns: [{ id: "order", width: sizes.custom(160, 280, 190).size }],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["order", "actions"]),
		rowHeight: 56,
		headerHeight: 45,
		style: "compact",
	},
	"inventory-production-plan": {
		tableId: "inventory-production-plan",
		stickyColumns: [
			{ id: "component", width: sizes.custom(200, 380, 250).size },
		],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["component", "actions"]),
		rowHeight: 56,
		headerHeight: 45,
		style: "compact",
	},
	"inventory-kind-review": {
		tableId: "inventory-kind-review",
		stickyColumns: [{ id: "item", width: sizes.custom(200, 380, 250).size }],
		sortFieldMap: {
			item: "name",
		},
		nonReorderableColumns: new Set(["item", "actions"]),
		rowHeight: 56,
		headerHeight: 45,
		style: "compact",
	},
	"inventory-stock-audit": {
		tableId: "inventory-stock-audit",
		stickyColumns: [
			{ id: "category", width: sizes.custom(160, 260, 190).size },
		],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["category"]),
		rowHeight: 56,
		headerHeight: 45,
		style: "compact",
	},
	"inventory-item-variants": {
		tableId: "inventory-item-variants",
		stickyColumns: [{ id: "variant", width: sizes.custom(220, 420, 280).size }],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["variant", "actions"]),
		rowHeight: 72,
		headerHeight: 45,
		style: "compact",
	},
	"inventory-item-stocks": {
		tableId: "inventory-item-stocks",
		stickyColumns: [{ id: "variant", width: sizes.custom(200, 340, 240).size }],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["variant", "actions"]),
		rowHeight: 56,
		headerHeight: 45,
		style: "compact",
	},
	"inventory-item-movements": {
		tableId: "inventory-item-movements",
		stickyColumns: [{ id: "event", width: sizes.custom(150, 220, 170).size }],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["event"]),
		rowHeight: 56,
		headerHeight: 45,
		style: "compact",
	},
	"inventory-item-inbound-demands": {
		tableId: "inventory-item-inbound-demands",
		stickyColumns: [{ id: "variant", width: sizes.custom(160, 260, 190).size }],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["variant", "actions"]),
		rowHeight: 56,
		headerHeight: 45,
		style: "compact",
	},
	"inventory-item-allocations": {
		tableId: "inventory-item-allocations",
		stickyColumns: [{ id: "variant", width: sizes.custom(160, 260, 190).size }],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["variant", "actions"]),
		rowHeight: 56,
		headerHeight: 45,
		style: "compact",
	},
	"inventory-item-related-lines": {
		tableId: "inventory-item-related-lines",
		stickyColumns: [{ id: "order", width: sizes.custom(150, 240, 170).size }],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["order", "actions"]),
		rowHeight: 56,
		headerHeight: 45,
		style: "compact",
	},
	"community-builders": {
		tableId: "community-builders",
		stickyColumns: [{ id: "builder", width: sizes.custom(220, 420, 280).size }],
		sortFieldMap: {
			builder: "name",
		},
		nonReorderableColumns: new Set(["builder", "actions"]),
		rowHeight: 64,
		headerHeight: 45,
		style: "compact",
	},
	"community-templates": {
		tableId: "community-templates",
		stickyColumns: [{ id: "model", width: sizes.custom(240, 440, 320).size }],
		sortFieldMap: {
			model: "modelName",
		},
		nonReorderableColumns: new Set(["model", "actions"]),
		rowHeight: 64,
		headerHeight: 45,
		style: "compact",
	},
	"community-install-costs": {
		tableId: "community-install-costs",
		stickyColumns: [{ id: "task", width: sizes.custom(220, 420, 280).size }],
		sortFieldMap: {},
		nonReorderableColumns: new Set(["task", "actions"]),
		rowHeight: 48,
		headerHeight: 45,
		style: "compact",
	},
	"customer-service": {
		tableId: "customer-service",
		stickyColumns: [
			{ id: "select", width: sizes.custom(50, 50).size },
			{ id: "appointment", width: sizes.custom(132, 210, 154).size },
		],
		sortFieldMap: {
			appointment: "scheduleDate",
			customer: "homeOwner",
			status: "status",
		},
		nonReorderableColumns: new Set(["select", "appointment", "actions"]),
		rowHeight: 56,
		headerHeight: 45,
		style: "compact",
	},
	"unit-invoices": {
		tableId: "unit-invoices",
		stickyColumns: [
			{ id: "lotBlock", width: sizes.custom(220, 380, 280).size },
		],
		sortFieldMap: {
			lotBlock: "lotBlock",
			project: "project",
			date: "date",
		},
		nonReorderableColumns: new Set(["lotBlock", "actions"]),
		rowHeight: 64,
		headerHeight: 45,
		style: "compact",
	},
	"unit-productions": {
		tableId: "unit-productions",
		stickyColumns: [
			{ id: "select", width: sizes.custom(50, 50).size },
			{ id: "dueDate", width: sizes.custom(150, 220, 170).size },
		],
		sortFieldMap: {
			dueDate: "dueDate",
			task: "task",
			unit: "unit",
			project: "project",
		},
		nonReorderableColumns: new Set(["select", "dueDate", "actions"]),
		rowHeight: 64,
		headerHeight: 45,
		style: "compact",
	},
};

export function getTableConfig(tableId: TableId) {
	return TABLE_CONFIGS[tableId];
}

export const STICKY_COLUMNS = Object.fromEntries(
	Object.entries(TABLE_CONFIGS).map(([tableId, config]) => [
		tableId,
		config.stickyColumns,
	]),
) as Record<TableId, StickyColumnConfig[]>;

export const SORT_FIELD_MAPS = Object.fromEntries(
	Object.entries(TABLE_CONFIGS).map(([tableId, config]) => [
		tableId,
		config.sortFieldMap,
	]),
) as Record<TableId, Record<string, string>>;

export const NON_REORDERABLE_COLUMNS = Object.fromEntries(
	Object.entries(TABLE_CONFIGS).map(([tableId, config]) => [
		tableId,
		config.nonReorderableColumns,
	]),
) as Record<TableId, Set<string>>;

export const ROW_HEIGHTS = Object.fromEntries(
	Object.entries(TABLE_CONFIGS).map(([tableId, config]) => [
		tableId,
		config.rowHeight,
	]),
) as Record<TableId, number>;

export const SUMMARY_GRID_HEIGHTS = Object.fromEntries(
	Object.entries(TABLE_CONFIGS)
		.filter(([, config]) => config.summaryGridHeight !== undefined)
		.map(([tableId, config]) => [tableId, config.summaryGridHeight]),
) as Partial<Record<TableId, number>>;
