/** @jsxImportSource react */
import type { IconKeys } from "../../icons";

export const searchIcons: Partial<{
	[id in string]: IconKeys;
}> = {
	q: "Search",
	address: "address",
	orderNo: "orders",
	salesNo: "orders",
	"customer.name": "user",
	customerName: "user",
	phone: "phone",
	search: "Search",
	"production.assignedToId": "production",
	"production.assignment": "production",
	"production.status": "production",
	production: "production",
	"production.dueDate": "calendar",
	scheduleDate: "calendar",
	po: "post",
	"sales.rep": "user",
	"sales.priority": "flag",
	priority: "flag",
	salesRepId: "user",
	invoice: "invoice",
	invoiceStatus: "invoice",
	item: "products",
	paymentReview: "payment",
	salesChannel: "Share",
	inbound: "inbound",
	specialOrder: "PenTool",
	specialOrderScope: "PenTool",
	"salesRep.id": "user",
	"dispatch.status": "dispatch",
	status: "Status",
	dateRange: "calendar",
	dueDateRange: "calendar",
	agingBuckets: "calendar",
	showing: "monitor",
	show: "monitor",
	category: "category",
	categoryId: "category",
	reportCategory: "category",
	payments: "cash",
	paymentType: "payment",
	paymentMethod: "payment",
	paymentMethods: "payment",
	paymentStatus: "Status",
	paymentStatuses: "Status",
	statuses: "Status",
	applicationStatus: "accounting",
	applicationStatuses: "accounting",
	exceptionCode: "warning",
	exceptionCodes: "warning",
	project: "project",
	projectId: "project",
	projectSlug: "project",
	builder: "user",
	builderId: "user",
	builderSlug: "user",
	template: "template",
	installCost: "installCosts",
	contractor: "user",
	contractorIds: "user",
	entryTypes: "accounting",
	sourceTypes: "documents",
	amountBand: "Currency",
	exceptionsOnly: "warning",
	authorizedBy: "user",
	role: "roles",
	profile: "profile",
	refNo: "post",
	taskNames: "tasks",
	installation: "installation",
};

export function isSearchKey(k) {
	return k === "q" || k === "search" || k?.startsWith("_q");
}
export function getSearchKey(filters) {
	return Object.entries(filters || {}).find(([k, v]) => isSearchKey(k))?.[0];
}
