-- CreateTable
CREATE TABLE `SalesHandoffActionEpoch` (
    `id` VARCHAR(191) NOT NULL,
    `salesOrderId` INTEGER NOT NULL,
    `orderId` VARCHAR(255) NOT NULL,
    `actionType` VARCHAR(32) NOT NULL,
    `epoch` INTEGER NOT NULL,
    `openKey` VARCHAR(191) NULL,
    `responsibleRepId` INTEGER NOT NULL,
    `organizationId` INTEGER NULL,
    `policyRevision` INTEGER NOT NULL,
    `evidenceRevision` VARCHAR(191) NOT NULL,
    `uncoveredQty` DOUBLE NOT NULL DEFAULT 0,
    `qualifiedAt` TIMESTAMP(0) NULL,
    `openedAt` TIMESTAMP(0) NOT NULL,
    `openedByUserId` INTEGER NULL,
    `targetSalesItemId` INTEGER NULL,
    `targetControlUid` VARCHAR(191) NULL,
    `targetAssignmentId` INTEGER NULL,
    `escalationDueAt` TIMESTAMP(0) NULL,
    `escalatedAt` TIMESTAMP(0) NULL,
    `resolvedAt` TIMESTAMP(0) NULL,
    `resolvedByUserId` INTEGER NULL,
    `resolutionReason` VARCHAR(64) NULL,
    `reopenedFromEpochId` VARCHAR(191) NULL,
    `lastReconciledAt` TIMESTAMP(0) NOT NULL,
    `lastReconciledByUserId` INTEGER NULL,
    `source` VARCHAR(32) NOT NULL DEFAULT 'projection',
    `createdAt` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `SalesHandoffActionEpoch_openKey_key`(`openKey`),
    INDEX `idx_sales_handoff_rep_queue`(`actionType`, `responsibleRepId`, `resolvedAt`, `openedAt`),
    INDEX `idx_sales_handoff_admin_queue`(`actionType`, `resolvedAt`, `openedAt`),
    INDEX `idx_sales_handoff_org_queue`(`organizationId`, `resolvedAt`, `openedAt`),
    INDEX `idx_sales_handoff_order_action`(`salesOrderId`, `actionType`, `resolvedAt`),
    INDEX `idx_sales_handoff_escalation_scan`(`resolvedAt`, `escalatedAt`, `escalationDueAt`, `id`),
    INDEX `idx_sales_handoff_evidence`(`evidenceRevision`),
    UNIQUE INDEX `SalesHandoffActionEpoch_salesOrderId_actionType_epoch_key`(`salesOrderId`, `actionType`, `epoch`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `SalesHandoffActionEscalationRecipient` (
    `id` VARCHAR(191) NOT NULL,
    `actionEpochId` VARCHAR(191) NOT NULL,
    `recipientUserId` INTEGER NOT NULL,
    `notificationActivityId` INTEGER NULL,
    `notifiedAt` TIMESTAMP(0) NULL,
    `acknowledgedAt` TIMESTAMP(0) NULL,
    `createdAt` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `updatedAt` DATETIME(3) NOT NULL,

    INDEX `idx_sales_handoff_notification_activity`(`notificationActivityId`),
    INDEX `idx_sales_handoff_recipient_ack`(`recipientUserId`, `acknowledgedAt`, `notifiedAt`),
    UNIQUE INDEX `SalesHandoffActionEscalationRecipient_actionEpochId_recipien_key`(`actionEpochId`, `recipientUserId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `SalesPackingReport` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `salesOrderId` INTEGER NOT NULL,
    `orderDeliveryId` INTEGER NOT NULL,
    `salesOrderItemId` INTEGER NOT NULL,
    `orderProductionSubmissionId` INTEGER NOT NULL,
    `dispatchAllocationItemId` INTEGER NOT NULL,
    `submittedById` INTEGER NOT NULL,
    `reviewedById` INTEGER NULL,
    `status` ENUM('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED') NOT NULL DEFAULT 'PENDING',
    `reason` ENUM('UPSTREAM_PRODUCTION_REVIEW', 'STALE_UPSTREAM_EVIDENCE') NOT NULL,
    `idempotencyKey` VARCHAR(128) NOT NULL,
    `openKey` VARCHAR(191) NULL,
    `qty` INTEGER NOT NULL,
    `lhQty` INTEGER NOT NULL DEFAULT 0,
    `rhQty` INTEGER NOT NULL DEFAULT 0,
    `manifestRevision` VARCHAR(64) NOT NULL,
    `dispatchAllocationKey` VARCHAR(64) NOT NULL,
    `evidenceSnapshot` JSON NOT NULL,
    `note` TEXT NULL,
    `decisionNote` TEXT NULL,
    `submittedAt` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `reviewedAt` TIMESTAMP(0) NULL,
    `rejectedAt` TIMESTAMP(0) NULL,
    `cancelledAt` TIMESTAMP(0) NULL,
    `createdAt` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `SalesPackingReport_idempotencyKey_key`(`idempotencyKey`),
    UNIQUE INDEX `SalesPackingReport_openKey_key`(`openKey`),
    INDEX `SalesPackingReport_status_submittedAt_idx`(`status`, `submittedAt`),
    INDEX `SalesPackingReport_orderDeliveryId_status_idx`(`orderDeliveryId`, `status`),
    INDEX `SalesPackingReport_orderDeliveryId_dispatchAllocationKey_idx`(`orderDeliveryId`, `dispatchAllocationKey`),
    INDEX `SalesPackingReport_salesOrderId_status_idx`(`salesOrderId`, `status`),
    INDEX `SalesPackingReport_salesOrderItemId_status_idx`(`salesOrderItemId`, `status`),
    INDEX `SalesPackingReport_orderProductionSubmissionId_status_idx`(`orderProductionSubmissionId`, `status`),
    INDEX `SalesPackingReport_dispatchAllocationItemId_idx`(`dispatchAllocationItemId`),
    INDEX `SalesPackingReport_submittedById_status_idx`(`submittedById`, `status`),
    INDEX `SalesPackingReport_reviewedById_idx`(`reviewedById`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
