CREATE TABLE `AssistantQuotaPolicy` (
  `id` VARCHAR(191) NOT NULL,
  `userId` INTEGER NULL,
  `name` VARCHAR(120) NOT NULL,
  `kind` VARCHAR(32) NOT NULL DEFAULT 'user',
  `sourceTemplateId` VARCHAR(191) NULL,
  `dailyRequestLimit` INTEGER NULL,
  `monthlyRequestLimit` INTEGER NULL,
  `dailyTokenLimit` BIGINT NULL,
  `monthlyTokenLimit` BIGINT NULL,
  `concurrentRunLimit` INTEGER NULL,
  `dailyCostLimitMicros` BIGINT NULL,
  `monthlyCostLimitMicros` BIGINT NULL,
  `warningPercent` INTEGER NOT NULL DEFAULT 80,
  `timezone` VARCHAR(64) NOT NULL DEFAULT 'UTC',
  `enforcementMode` VARCHAR(24) NOT NULL DEFAULT 'hard',
  `effectiveFrom` TIMESTAMP(0) NOT NULL,
  `effectiveTo` TIMESTAMP(0) NULL,
  `createdByUserId` INTEGER NOT NULL,
  `updatedByUserId` INTEGER NOT NULL,
  `version` INTEGER NOT NULL DEFAULT 1,
  `createdAt` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  `updatedAt` DATETIME(3) NOT NULL,

  INDEX `asst_quota_user_effective_idx`(`userId`, `effectiveFrom`, `effectiveTo`),
  INDEX `asst_quota_kind_effective_idx`(`kind`, `effectiveFrom`, `effectiveTo`),
  INDEX `asst_quota_template_idx`(`sourceTemplateId`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `AssistantQuotaReservation` (
  `id` VARCHAR(191) NOT NULL,
  `runId` VARCHAR(191) NOT NULL,
  `actorUserId` INTEGER NOT NULL,
  `scopeType` VARCHAR(50) NOT NULL,
  `scopeId` VARCHAR(191) NOT NULL,
  `policyId` VARCHAR(191) NULL,
  `policySnapshot` JSON NOT NULL,
  `status` VARCHAR(24) NOT NULL DEFAULT 'reserved',
  `requestUnits` INTEGER NOT NULL DEFAULT 1,
  `reservedTokens` BIGINT NOT NULL DEFAULT 0,
  `reservedCostMicros` BIGINT NOT NULL DEFAULT 0,
  `actualTokens` BIGINT NULL,
  `actualCostMicros` BIGINT NULL,
  `dayWindowStart` TIMESTAMP(0) NOT NULL,
  `monthWindowStart` TIMESTAMP(0) NOT NULL,
  `expiresAt` TIMESTAMP(0) NOT NULL,
  `settledAt` TIMESTAMP(0) NULL,
  `createdAt` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  `updatedAt` DATETIME(3) NOT NULL,

  UNIQUE INDEX `asst_quota_reservation_run_uq`(`runId`),
  INDEX `asst_quota_actor_day_idx`(`actorUserId`, `dayWindowStart`, `status`),
  INDEX `asst_quota_actor_month_idx`(`actorUserId`, `monthWindowStart`, `status`),
  INDEX `asst_quota_actor_active_idx`(`actorUserId`, `status`, `expiresAt`),
  INDEX `asst_quota_policy_usage_idx`(`policyId`, `createdAt`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
