-- CreateTable
CREATE TABLE `SalesRequestMailboxOAuthAttempt` (
    `stateDigest` VARCHAR(80) NOT NULL,
    `organizationId` INTEGER NOT NULL,
    `ownerUserId` INTEGER NOT NULL,
    `employeeProfileId` INTEGER NOT NULL,
    `officeAuthorityKey` VARCHAR(191) NOT NULL,
    `provider` VARCHAR(32) NOT NULL,
    `redirectKey` VARCHAR(64) NOT NULL,
    `issuedAt` DATETIME(3) NOT NULL,
    `expiresAt` DATETIME(3) NOT NULL,
    `salesSettingsId` INTEGER NOT NULL,
    `salesSettingsRevision` INTEGER NOT NULL,
    `policyRevision` INTEGER NOT NULL,
    `authorityRevision` VARCHAR(191) NOT NULL,
    `consumedAt` DATETIME(3) NULL,
    `terminalAt` DATETIME(3) NULL,
    `terminalReason` VARCHAR(64) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    INDEX `sales_req_mailbox_oauth_owner_idx`(`ownerUserId`, `provider`, `issuedAt`),
    INDEX `sales_req_mailbox_oauth_expiry_idx`(`expiresAt`, `consumedAt`),
    INDEX `sales_req_mailbox_oauth_terminal_idx`(`terminalAt`),
    PRIMARY KEY (`stateDigest`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `SalesRequestMailboxConnection` (
    `id` VARCHAR(191) NOT NULL,
    `organizationId` INTEGER NOT NULL,
    `ownerUserId` INTEGER NOT NULL,
    `employeeProfileId` INTEGER NOT NULL,
    `officeAuthorityKey` VARCHAR(191) NOT NULL,
    `authorityRevision` VARCHAR(191) NOT NULL,
    `salesSettingsId` INTEGER NOT NULL,
    `salesSettingsRevision` INTEGER NOT NULL,
    `policyRevision` INTEGER NOT NULL,
    `provider` VARCHAR(32) NOT NULL,
    `providerAccountId` VARCHAR(255) NULL,
    `providerAccountIdentityHash` CHAR(64) NULL,
    `accountEmail` VARCHAR(320) NULL,
    `displayName` VARCHAR(255) NULL,
    `grantedScopes` JSON NULL,
    `scopeFingerprint` VARCHAR(69) NULL,
    `accessTokenEnvelope` JSON NULL,
    `refreshTokenEnvelope` JSON NULL,
    `tokenExpiresAt` DATETIME(3) NULL,
    `revision` INTEGER NOT NULL DEFAULT 1,
    `state` VARCHAR(32) NOT NULL DEFAULT 'active',
    `automationMode` VARCHAR(32) NOT NULL DEFAULT 'manual',
    `notifyOnNeedsReview` BOOLEAN NOT NULL DEFAULT false,
    `excludedSenders` JSON NOT NULL,
    `excludedDomains` JSON NOT NULL,
    `syncBlocked` BOOLEAN NOT NULL DEFAULT false,
    `lastSyncAt` DATETIME(3) NULL,
    `healthOperationId` VARCHAR(255) NULL,
    `healthOperationReason` VARCHAR(32) NULL,
    `healthOperationConnectionRevision` INTEGER NULL,
    `healthStatus` VARCHAR(40) NOT NULL DEFAULT 'healthy',
    `healthLeaseId` VARCHAR(255) NULL,
    `healthLeaseEpoch` INTEGER NOT NULL DEFAULT 0,
    `healthLeaseExpiresAt` DATETIME(3) NULL,
    `healthRetryAttempt` INTEGER NOT NULL DEFAULT 0,
    `healthNextAttemptAt` DATETIME(3) NULL,
    `healthCheckedAt` DATETIME(3) NULL,
    `healthRefreshedAt` DATETIME(3) NULL,
    `healthErrorCode` VARCHAR(80) NULL,
    `disconnectId` VARCHAR(255) NULL,
    `disconnectPhase` VARCHAR(40) NULL,
    `disconnectPreviousRevision` INTEGER NULL,
    `disconnectStartedAt` DATETIME(3) NULL,
    `disconnectCompletedAt` DATETIME(3) NULL,
    `disconnectFailurePhase` VARCHAR(40) NULL,
    `disconnectFailureReason` VARCHAR(80) NULL,
    `disconnectFailureAt` DATETIME(3) NULL,
    `providerRevokedAt` DATETIME(3) NULL,
    `disconnectedAt` DATETIME(3) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `sales_req_mailbox_health_work_uq`(`healthOperationId`),
    UNIQUE INDEX `sales_req_mailbox_disconnect_work_uq`(`disconnectId`),
    INDEX `sales_req_mailbox_owner_state_idx`(`ownerUserId`, `organizationId`, `state`, `updatedAt`),
    INDEX `sales_req_mailbox_admin_health_idx`(`organizationId`, `state`, `healthStatus`, `updatedAt`),
    INDEX `sales_req_mailbox_health_due_idx`(`state`, `syncBlocked`, `healthNextAttemptAt`),
    INDEX `sales_req_mailbox_disconnect_idx`(`disconnectPhase`, `disconnectStartedAt`),
    UNIQUE INDEX `SalesRequestMailboxConnection_provider_providerAccountIdenti_key`(`provider`, `providerAccountIdentityHash`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `SalesRequestMailboxSource` (
    `id` VARCHAR(191) NOT NULL,
    `connectionId` VARCHAR(191) NOT NULL,
    `kind` VARCHAR(32) NOT NULL,
    `providerSourceId` VARCHAR(255) NOT NULL,
    `providerSourceIdentityHash` CHAR(64) NOT NULL,
    `sourceKey` VARCHAR(255) NOT NULL,
    `sourceKeyIdentityHash` CHAR(64) NOT NULL,
    `selected` BOOLEAN NOT NULL DEFAULT true,
    `revision` INTEGER NOT NULL DEFAULT 1,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    INDEX `sales_req_mailbox_source_selected_idx`(`connectionId`, `selected`, `revision`),
    UNIQUE INDEX `SalesRequestMailboxSource_connectionId_sourceKeyIdentityHash_key`(`connectionId`, `sourceKeyIdentityHash`),
    UNIQUE INDEX `SalesRequestMailboxSource_connectionId_kind_providerSourceId_key`(`connectionId`, `kind`, `providerSourceIdentityHash`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `SalesRequestMailboxSyncStream` (
    `id` VARCHAR(191) NOT NULL,
    `connectionId` VARCHAR(191) NOT NULL,
    `sourceId` VARCHAR(191) NOT NULL,
    `status` VARCHAR(32) NOT NULL DEFAULT 'queued',
    `checkpointMode` VARCHAR(32) NULL,
    `checkpointCursor` TEXT NULL,
    `checkpointPageToken` TEXT NULL,
    `checkpointSince` DATETIME(3) NULL,
    `checkpointRetryAttempts` INTEGER NOT NULL DEFAULT 0,
    `checkpointCursorResets` INTEGER NOT NULL DEFAULT 0,
    `continuationFingerprints` JSON NULL,
    `checkpointHash` VARCHAR(80) NULL,
    `runId` VARCHAR(255) NULL,
    `leaseId` VARCHAR(255) NULL,
    `leaseEpoch` INTEGER NOT NULL DEFAULT 0,
    `leaseExpiresAt` DATETIME(3) NULL,
    `leasedConnectionRevision` INTEGER NULL,
    `leasedPolicyRevision` INTEGER NULL,
    `nextAttemptAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `failureCode` VARCHAR(80) NULL,
    `failureEvidence` JSON NULL,
    `lastPagesFetched` INTEGER NOT NULL DEFAULT 0,
    `lastMessagesProjected` INTEGER NOT NULL DEFAULT 0,
    `lastMessagesSuppressed` INTEGER NOT NULL DEFAULT 0,
    `lastTombstonesProjected` INTEGER NOT NULL DEFAULT 0,
    `completedAt` DATETIME(3) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    INDEX `sales_req_mailbox_stream_due_idx`(`status`, `nextAttemptAt`, `leaseExpiresAt`),
    INDEX `sales_req_mailbox_stream_lease_idx`(`leaseId`, `leaseEpoch`),
    UNIQUE INDEX `SalesRequestMailboxSyncStream_connectionId_sourceId_key`(`connectionId`, `sourceId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `SalesRequestMailboxMessageSummary` (
    `id` VARCHAR(191) NOT NULL,
    `connectionId` VARCHAR(191) NOT NULL,
    `sourceId` VARCHAR(191) NOT NULL,
    `provider` VARCHAR(32) NOT NULL,
    `providerMessageId` VARCHAR(255) NOT NULL,
    `providerMessageIdentityHash` CHAR(64) NOT NULL,
    `providerThreadId` VARCHAR(255) NULL,
    `providerFolderId` VARCHAR(255) NULL,
    `providerLabelIds` JSON NOT NULL,
    `fromEmail` VARCHAR(320) NOT NULL,
    `fromName` VARCHAR(255) NULL,
    `subject` VARCHAR(998) NULL,
    `receivedAt` DATETIME(3) NOT NULL,
    `hasAttachments` BOOLEAN NOT NULL DEFAULT false,
    `automationHeaders` JSON NOT NULL,
    `projectionHash` VARCHAR(80) NOT NULL,
    `summaryRevision` INTEGER NOT NULL DEFAULT 1,
    `disposition` VARCHAR(32) NOT NULL DEFAULT 'accepted',
    `exclusionReason` VARCHAR(64) NULL,
    `active` BOOLEAN NOT NULL DEFAULT true,
    `detailStatus` VARCHAR(32) NOT NULL DEFAULT 'queued',
    `tombstonedAt` DATETIME(3) NULL,
    `projectedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    INDEX `sales_req_mailbox_summary_detail_idx`(`detailStatus`, `active`, `projectedAt`),
    INDEX `sales_req_mailbox_summary_message_idx`(`connectionId`, `providerMessageIdentityHash`),
    UNIQUE INDEX `SalesRequestMailboxMessageSummary_connectionId_sourceId_prov_key`(`connectionId`, `sourceId`, `providerMessageIdentityHash`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `SalesRequestMailboxMessageLease` (
    `id` VARCHAR(191) NOT NULL,
    `connectionId` VARCHAR(191) NOT NULL,
    `providerMessageId` VARCHAR(255) NOT NULL,
    `providerMessageIdentityHash` CHAR(64) NOT NULL,
    `sourceId` VARCHAR(191) NOT NULL,
    `claimedSummaryId` VARCHAR(191) NULL,
    `claimedSummaryRevision` INTEGER NULL,
    `sourceMembershipIdentity` VARCHAR(69) NULL,
    `status` VARCHAR(32) NOT NULL DEFAULT 'queued',
    `runId` VARCHAR(255) NULL,
    `leaseId` VARCHAR(255) NULL,
    `leaseEpoch` INTEGER NOT NULL DEFAULT 0,
    `leaseExpiresAt` DATETIME(3) NULL,
    `leasedConnectionRevision` INTEGER NULL,
    `leasedPolicyRevision` INTEGER NULL,
    `retryAttempts` INTEGER NOT NULL DEFAULT 0,
    `nextAttemptAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `failureCode` VARCHAR(80) NULL,
    `failureEvidence` JSON NULL,
    `completedAt` DATETIME(3) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    INDEX `sales_req_mailbox_lease_due_idx`(`status`, `nextAttemptAt`, `leaseExpiresAt`),
    INDEX `sales_req_mailbox_lease_fence_idx`(`leaseId`, `leaseEpoch`),
    UNIQUE INDEX `SalesRequestMailboxMessageLease_connectionId_providerMessage_key`(`connectionId`, `providerMessageIdentityHash`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `SalesRequestMailboxSourceMembership` (
    `id` VARCHAR(69) NOT NULL,
    `connectionId` VARCHAR(191) NOT NULL,
    `sourceId` VARCHAR(191) NOT NULL,
    `messageSummaryId` VARCHAR(191) NOT NULL,
    `snapshotId` VARCHAR(191) NOT NULL,
    `providerMessageId` VARCHAR(255) NOT NULL,
    `providerMessageIdentityHash` CHAR(64) NOT NULL,
    `summaryRevision` INTEGER NOT NULL,
    `state` VARCHAR(32) NOT NULL DEFAULT 'active',
    `activeKey` VARCHAR(512) NULL,
    `activatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `deactivatedAt` DATETIME(3) NULL,
    `withdrawalReason` VARCHAR(80) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `sales_req_mailbox_membership_active_uq`(`activeKey`),
    INDEX `sales_req_mailbox_membership_active_idx`(`connectionId`, `providerMessageIdentityHash`, `state`),
    INDEX `sales_req_mailbox_membership_snapshot_idx`(`snapshotId`, `state`),
    UNIQUE INDEX `SalesRequestMailboxSourceMembership_sourceId_providerMessage_key`(`sourceId`, `providerMessageIdentityHash`, `summaryRevision`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `SalesRequestMailboxMessageSnapshot` (
    `id` VARCHAR(191) NOT NULL,
    `connectionId` VARCHAR(191) NOT NULL,
    `provider` VARCHAR(32) NOT NULL,
    `providerMessageId` VARCHAR(255) NOT NULL,
    `providerMessageIdentityHash` CHAR(64) NOT NULL,
    `providerThreadId` VARCHAR(255) NULL,
    `schemaVersion` INTEGER NOT NULL DEFAULT 1,
    `contentHash` VARCHAR(69) NOT NULL,
    `capturedAt` DATETIME(3) NOT NULL,
    `receivedAt` DATETIME(3) NOT NULL,
    `expiresAt` DATETIME(3) NOT NULL,
    `fromEmail` VARCHAR(320) NOT NULL,
    `fromName` VARCHAR(255) NULL,
    `subject` VARCHAR(998) NULL,
    `toEmails` JSON NOT NULL,
    `ccEmails` JSON NOT NULL,
    `hasAttachments` BOOLEAN NOT NULL DEFAULT false,
    `displayText` LONGTEXT NOT NULL,
    `modelInput` LONGTEXT NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `sales_req_mailbox_snapshot_expiry_idx`(`expiresAt`),
    INDEX `sales_req_mailbox_snapshot_message_idx`(`connectionId`, `providerMessageIdentityHash`, `receivedAt`),
    UNIQUE INDEX `SalesRequestMailboxMessageSnapshot_connectionId_providerMess_key`(`connectionId`, `providerMessageIdentityHash`, `schemaVersion`, `contentHash`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `SalesRequestMailboxQueueProjection` (
    `id` VARCHAR(191) NOT NULL,
    `queueIdentity` VARCHAR(80) NOT NULL,
    `connectionId` VARCHAR(191) NOT NULL,
    `organizationId` INTEGER NOT NULL,
    `ownerUserId` INTEGER NOT NULL,
    `provider` VARCHAR(32) NOT NULL,
    `providerMessageId` VARCHAR(255) NOT NULL,
    `providerMessageIdentityHash` CHAR(64) NOT NULL,
    `snapshotId` VARCHAR(191) NOT NULL,
    `sourceMembershipId` VARCHAR(69) NOT NULL,
    `sourceKey` VARCHAR(255) NOT NULL,
    `sourceSummaryRevision` INTEGER NOT NULL,
    `snapshotSchemaVersion` INTEGER NOT NULL DEFAULT 1,
    `contentHash` VARCHAR(69) NOT NULL,
    `status` VARCHAR(32) NOT NULL DEFAULT 'new',
    `statusRevision` INTEGER NOT NULL DEFAULT 1,
    `statusUpdatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `failureCode` VARCHAR(80) NULL,
    `receivedAt` DATETIME(3) NOT NULL,
    `fromEmail` VARCHAR(320) NOT NULL,
    `fromName` VARCHAR(255) NULL,
    `subject` VARCHAR(998) NULL,
    `hasAttachments` BOOLEAN NOT NULL DEFAULT false,
    `withdrawnAt` DATETIME(3) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `sales_req_mailbox_queue_identity_uq`(`queueIdentity`),
    INDEX `sales_req_mailbox_inbox_idx`(`ownerUserId`, `organizationId`, `connectionId`, `status`, `receivedAt`, `queueIdentity`),
    INDEX `sales_req_mailbox_inbox_all_idx`(`ownerUserId`, `organizationId`, `connectionId`, `receivedAt`, `queueIdentity`),
    INDEX `sales_req_mailbox_queue_snapshot_idx`(`snapshotId`),
    INDEX `sales_req_mailbox_queue_membership_idx`(`sourceMembershipId`),
    UNIQUE INDEX `SalesRequestMailboxQueueProjection_connectionId_providerMess_key`(`connectionId`, `providerMessageIdentityHash`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
