-- CreateTable
CREATE TABLE `SalesRequestGenerationRun` (
    `generationId` VARCHAR(36) NOT NULL,
    `actorUserId` INTEGER NULL,
    `scope` VARCHAR(191) NOT NULL,
    `configurationRevision` VARCHAR(128) NOT NULL,
    `provider` VARCHAR(32) NOT NULL,
    `model` VARCHAR(100) NOT NULL,
    `promptVersion` VARCHAR(64) NULL,
    `schemaVersion` INTEGER NULL,
    `status` VARCHAR(32) NOT NULL,
    `failureStage` VARCHAR(32) NULL,
    `hasText` BOOLEAN NOT NULL DEFAULT false,
    `latencyMs` INTEGER NULL,
    `inputTokens` INTEGER NULL,
    `outputTokens` INTEGER NULL,
    `issueCounts` JSON NULL,
    `applyOutcome` VARCHAR(32) NULL,
    `applyAt` TIMESTAMP(0) NULL,
    `saveDraftOutcome` VARCHAR(32) NULL,
    `saveDraftAt` TIMESTAMP(0) NULL,
    `saveFinalOutcome` VARCHAR(32) NULL,
    `saveFinalAt` TIMESTAMP(0) NULL,
    `feedbackOutcome` VARCHAR(32) NULL,
    `feedbackIssueCategories` JSON NULL,
    `feedbackChangedFieldCategories` JSON NULL,
    `feedbackAt` TIMESTAMP(0) NULL,
    `correctionMs` INTEGER NULL,
    `startedAt` TIMESTAMP(0) NOT NULL,
    `completedAt` TIMESTAMP(0) NULL,
    `retentionUntil` TIMESTAMP(0) NOT NULL,
    `createdAt` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `updatedAt` DATETIME(3) NOT NULL,
    `deletedAt` TIMESTAMP(0) NULL,

    INDEX `sales_req_gen_status_created_idx`(`status`, `createdAt`),
    INDEX `sales_req_gen_actor_created_idx`(`actorUserId`, `createdAt`),
    INDEX `sales_req_gen_scope_created_idx`(`scope`, `createdAt`),
    INDEX `sales_req_gen_retention_idx`(`retentionUntil`, `deletedAt`),
    PRIMARY KEY (`generationId`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
