CREATE TABLE `StoredDocument` (
  `id` varchar(191) NOT NULL,
  `kind` varchar(100) NOT NULL,
  `ownerType` varchar(100) NOT NULL,
  `ownerId` varchar(191) NOT NULL,
  `ownerKey` varchar(191) DEFAULT NULL,
  `provider` varchar(100) NOT NULL,
  `pathname` varchar(512) NOT NULL,
  `url` varchar(512) DEFAULT NULL,
  `filename` varchar(255) DEFAULT NULL,
  `mimeType` varchar(255) DEFAULT NULL,
  `extension` varchar(50) DEFAULT NULL,
  `size` int DEFAULT NULL,
  `checksum` varchar(191) DEFAULT NULL,
  `visibility` varchar(50) NOT NULL DEFAULT 'private',
  `status` varchar(50) NOT NULL DEFAULT 'ready',
  `isCurrent` tinyint(1) NOT NULL DEFAULT 1,
  `generated` tinyint(1) NOT NULL DEFAULT 0,
  `sourceType` varchar(100) DEFAULT NULL,
  `sourceId` varchar(191) DEFAULT NULL,
  `uploadedBy` int DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `description` longtext DEFAULT NULL,
  `meta` json DEFAULT NULL,
  `createdAt` datetime DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deletedAt` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `StoredDocument_ownerType_ownerId_kind_status_idx` (`ownerType`, `ownerId`, `kind`, `status`),
  KEY `StoredDocument_ownerType_ownerId_kind_isCurrent_idx` (`ownerType`, `ownerId`, `kind`, `isCurrent`),
  KEY `StoredDocument_kind_status_updatedAt_idx` (`kind`, `status`, `updatedAt`),
  KEY `StoredDocument_provider_pathname_idx` (`provider`, `pathname`),
  KEY `StoredDocument_sourceType_sourceId_idx` (`sourceType`, `sourceId`),
  KEY `StoredDocument_uploadedBy_idx` (`uploadedBy`)
);

CREATE TABLE `SalesDocumentSnapshot` (
  `id` varchar(191) NOT NULL,
  `salesOrderId` int NOT NULL,
  `storedDocumentId` varchar(191) DEFAULT NULL,
  `documentType` varchar(100) NOT NULL,
  `version` int NOT NULL DEFAULT 1,
  `generationStatus` varchar(50) NOT NULL DEFAULT 'pending',
  `reason` varchar(100) DEFAULT NULL,
  `isCurrent` tinyint(1) NOT NULL DEFAULT 1,
  `sourceUpdatedAt` datetime DEFAULT NULL,
  `generatedAt` datetime DEFAULT NULL,
  `invalidatedAt` datetime DEFAULT NULL,
  `failedAt` datetime DEFAULT NULL,
  `errorMessage` longtext DEFAULT NULL,
  `meta` json DEFAULT NULL,
  `createdAt` datetime DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deletedAt` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `SalesDocumentSnapshot_salesOrderId_documentType_version_key` (`salesOrderId`, `documentType`, `version`),
  KEY `SalesDocumentSnapshot_salesOrderId_documentType_isCurrent_idx` (`salesOrderId`, `documentType`, `isCurrent`),
  KEY `SalesDocumentSnapshot_storedDocumentId_idx` (`storedDocumentId`),
  KEY `SalesDocumentSnapshot_generationStatus_updatedAt_idx` (`generationStatus`, `updatedAt`)
);
