import type { ErrorCode, ErrorDescriptor } from "./types";

export const ERROR_DESCRIPTORS: Record<ErrorCode, ErrorDescriptor> = {
	AUTHENTICATION_REQUIRED: {
		action: "sign_in",
		category: "authentication",
		code: "AUTHENTICATION_REQUIRED",
		publicMessage: "Sign in again to continue.",
		reportable: false,
		retryable: false,
		severity: "info",
		title: "Sign in required",
		transportCode: "UNAUTHORIZED",
	},
	CONFLICT: {
		action: "refresh",
		category: "conflict",
		code: "CONFLICT",
		publicMessage:
			"This record changed before your request completed. Refresh and try again.",
		reportable: false,
		retryable: false,
		severity: "warning",
		title: "This information has changed",
		transportCode: "CONFLICT",
	},
	DATABASE_CONSTRAINT: {
		action: "refresh",
		category: "database",
		code: "DATABASE_CONSTRAINT",
		publicMessage:
			"This change conflicts with existing information. Refresh and try again.",
		reportable: true,
		retryable: false,
		severity: "warning",
		title: "This change could not be saved",
		transportCode: "CONFLICT",
	},
	DATABASE_POOL_TIMEOUT: {
		action: "retry",
		category: "database",
		code: "DATABASE_POOL_TIMEOUT",
		publicMessage:
			"The system is temporarily busy. Please wait a moment and try again.",
		reportable: true,
		retryable: true,
		severity: "error",
		title: "The system is temporarily busy",
		transportCode: "INTERNAL_SERVER_ERROR",
	},
	DATABASE_TRANSACTION_TIMEOUT: {
		action: "retry",
		category: "database",
		code: "DATABASE_TRANSACTION_TIMEOUT",
		publicMessage:
			"We couldn't complete this action because the system took too long. Please try again.",
		reportable: true,
		retryable: true,
		severity: "error",
		title: "This is taking longer than expected",
		transportCode: "INTERNAL_SERVER_ERROR",
	},
	DATABASE_WRITE_CONFLICT: {
		action: "retry",
		category: "database",
		code: "DATABASE_WRITE_CONFLICT",
		publicMessage:
			"Another update happened at the same time. Please try again.",
		reportable: true,
		retryable: true,
		severity: "warning",
		title: "Another update happened first",
		transportCode: "CONFLICT",
	},
	NETWORK_UNAVAILABLE: {
		action: "retry",
		category: "network",
		code: "NETWORK_UNAVAILABLE",
		publicMessage:
			"We couldn't reach the service. Check your connection and try again.",
		reportable: false,
		retryable: true,
		severity: "warning",
		title: "Connection problem",
		transportCode: "INTERNAL_SERVER_ERROR",
	},
	NOT_FOUND: {
		category: "not_found",
		code: "NOT_FOUND",
		publicMessage: "The requested information could not be found.",
		reportable: false,
		retryable: false,
		severity: "info",
		title: "Information not found",
		transportCode: "NOT_FOUND",
	},
	PERMISSION_DENIED: {
		category: "permission",
		code: "PERMISSION_DENIED",
		publicMessage: "You do not have permission to perform this action.",
		reportable: false,
		retryable: false,
		severity: "info",
		title: "Permission required",
		transportCode: "FORBIDDEN",
	},
	PROVIDER_UNAVAILABLE: {
		action: "retry",
		category: "provider",
		code: "PROVIDER_UNAVAILABLE",
		publicMessage:
			"A connected service is temporarily unavailable. Please try again.",
		reportable: true,
		retryable: true,
		severity: "error",
		title: "A connected service is unavailable",
		transportCode: "INTERNAL_SERVER_ERROR",
	},
	RATE_LIMITED: {
		action: "retry",
		category: "rate_limit",
		code: "RATE_LIMITED",
		publicMessage: "Too many requests were made. Please wait and try again.",
		reportable: false,
		retryable: true,
		severity: "warning",
		title: "Please wait a moment",
		transportCode: "TOO_MANY_REQUESTS",
	},
	UNEXPECTED: {
		action: "contact_support",
		category: "unexpected",
		code: "UNEXPECTED",
		publicMessage: "Something went wrong. Please try again.",
		reportable: true,
		retryable: false,
		severity: "error",
		title: "Something went wrong",
		transportCode: "INTERNAL_SERVER_ERROR",
	},
	VALIDATION_FAILED: {
		category: "validation",
		code: "VALIDATION_FAILED",
		publicMessage: "Review the information provided and try again.",
		reportable: false,
		retryable: false,
		severity: "info",
		title: "Check the information provided",
		transportCode: "BAD_REQUEST",
	},
};
