import type { PageTabItem } from "@/components/page-tabs";

type SalesProductionTabCounts = {
	queueCount: number;
	dueTodayCount: number;
	unscheduledCount: number;
	pastDueCount: number;
	awaitingReviewCount: number;
	completedCount: number;
};

export function createSalesProductionPageTabs({
	queueCount,
	dueTodayCount,
	unscheduledCount,
	pastDueCount,
	awaitingReviewCount,
	completedCount,
}: SalesProductionTabCounts): PageTabItem[] {
	return [
		{
			title: "Due Today",
			count: dueTodayCount,
			params: {
				tab: "queue",
				view: "table",
				queue: null,
				due: "today",
				date: null,
				production: null,
				productionDueDate: null,
				show: null,
				label: null,
				calendarView: null,
				calendarDate: null,
			},
		},
		{
			title: "Calendar",
			params: {
				tab: "calendar",
				view: "calendar",
				queue: null,
				due: null,
				date: null,
				material: null,
				sort: null,
				"customer.name": null,
				phone: null,
				po: null,
				item: null,
				"sales.rep": null,
				invoice: null,
				salesNo: null,
				production: null,
				productionDueDate: null,
				show: null,
				label: null,
			},
		},
		{
			title: "Unscheduled",
			count: unscheduledCount,
			params: {
				tab: "queue",
				view: "table",
				queue: null,
				due: "unscheduled",
				date: null,
				material: null,
				sort: null,
				production: null,
				productionDueDate: null,
				show: null,
				label: null,
				calendarView: null,
				calendarDate: null,
			},
		},
		{
			title: "Active",
			count: queueCount,
			params: {
				tab: "queue",
				view: "table",
				queue: null,
				due: null,
				date: null,
				material: null,
				sort: null,
				production: null,
				productionDueDate: null,
				show: null,
				label: null,
				calendarView: null,
				calendarDate: null,
			},
		},
		{
			title: "Past Due",
			count: pastDueCount,
			params: {
				tab: "queue",
				view: "table",
				queue: null,
				due: "overdue",
				date: null,
				production: null,
				productionDueDate: null,
				show: null,
				label: null,
				calendarView: null,
				calendarDate: null,
			},
		},
		{
			title: "Review",
			count: awaitingReviewCount,
			params: {
				tab: "reviews",
				view: "table",
				queue: null,
				due: null,
				date: null,
				material: null,
				sort: null,
				assignedToId: null,
				priority: null,
				"customer.name": null,
				phone: null,
				po: null,
				item: null,
				"sales.rep": null,
				invoice: null,
				salesNo: null,
				production: null,
				productionDueDate: null,
				show: null,
				label: null,
				calendarView: null,
				calendarDate: null,
			},
		},
		{
			title: "Completed",
			count: completedCount,
			params: {
				tab: "completed",
				view: "table",
				queue: null,
				due: null,
				date: null,
				production: null,
				productionDueDate: null,
				show: null,
				label: null,
				calendarView: null,
				calendarDate: null,
			},
		},
	];
}
