CREATE TABLE `SalesPrintData` (
  `id` varchar(191) NOT NULL,
  `salesOrderId` int NOT NULL,
  `documentType` varchar(100) NOT NULL,
  `templateId` varchar(100) NOT NULL DEFAULT 'template-2',
  `mode` varchar(50) NOT NULL,
  `dispatchId` int DEFAULT NULL,
  `scopeKey` varchar(191) DEFAULT NULL,
  `title` varchar(255) NOT NULL,
  `firstOrderId` varchar(191) DEFAULT NULL,
  `companyAddress` json NOT NULL,
  `pages` json NOT NULL,
  `sourceUpdatedAt` datetime DEFAULT NULL,
  `generatedAt` datetime DEFAULT NULL,
  `invalidatedAt` datetime DEFAULT NULL,
  `failedAt` datetime DEFAULT NULL,
  `status` varchar(50) NOT NULL DEFAULT 'ready',
  `reason` varchar(100) DEFAULT NULL,
  `errorMessage` longtext DEFAULT NULL,
  `meta` json DEFAULT NULL,
  `createdAt` datetime DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deletedAt` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `SalesPrintData_salesOrderId_documentType_templateId_key` (`salesOrderId`, `documentType`, `templateId`),
  KEY `SalesPrintData_salesOrderId_status_idx` (`salesOrderId`, `status`),
  KEY `SalesPrintData_status_updatedAt_idx` (`status`, `updatedAt`)
);
