export const COMMUNITY_BLOCKS_INVENTORY_CATEGORY_TITLE = "Community";
export const COMMUNITY_LISTINGS_INVENTORY_CATEGORY_TITLE = "Community Item";
export const COMMUNITY_SECTIONS_INVENTORY_CATEGORY_TITLE = "Community Sections";
